eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('userProfile/', include('userProfile.urls')),
    path("accounts/", include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetail, FilteredView, search_products

app_name = "products"

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path("search/", search_products, name="search_products"),
    path('<slug>/', ProductDetail.as_view(), name='product_details'),
    path("products/<slug>/", FilteredView.as_view(), name="category")
]

userProfile/urls.py
from django.urls import path
from .views import add_to_cart, CartView, remove_from_cart, remove_singleitem_from_cart, checkout, RegisterUser

app_name = "userProfile"

urlpatterns = [
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>',
         remove_from_cart, name='remove_from_cart'),
    path('remove-singleitem-from-cart/<slug>',
         remove_singleitem_from_cart, name='remove_singleitem'),
    path('cart/', CartView.as_view(), name='cart'),
    path("checkout/", checkout, name="checkout"),
    path("register/", RegisterUser.as_view(), name="register")
]

userProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
import uuid

# Create your models here.


class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    profile_image = models.ImageField(upload_to='profile')


class CartItems(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    is_paid = models.BooleanField(default=False)

    def get_total_cartitem_price(self):
        return self.quantity * self.product.price

    def get_total_amount(self):
        total = 0
        i = 0
        cart_items = CartItems.objects.filter(user=self.user)
        while i < cart_items.count():
            total += cart_items[i].get_total_cartitem_price()
            i += 1
        return total

    def get_cart_count(self):
        count = 0
        cart_items = CartItems.objects.filter(user=self.user)
        for item in cart_items:
            count = count + item.quantity
        return count


class Cart(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='cart')
    items = models.ManyToManyField(CartItems)
    is_paid = models.BooleanField(default=False)

userProfile/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView
from .models import Cart, CartItems
from products.models import Product
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
# Create your views here.


@login_required
def add_to_cart(request, slug):
    product = Product.objects.get(slug=slug)
    user = request.user
    cart = Cart.objects.filter(user=user, is_paid=False)
    cart_item, created = CartItems.objects.get_or_create(
        product=product, user=user, is_paid=False)
    if cart.exists():
        order = cart[0]
        if order.items.filter(product__slug=product.slug).exists():
            cart_item.quantity += 1
            cart_item.save()
        else:
            order.items.add(cart_item)
    else:
        order = Cart.objects.create(user=user, is_paid=False)
        order.items.add(cart_item)

    return redirect(reverse('userProfile:cart'))


class CartView(LoginRequiredMixin, ListView):
    model = CartItems
    template_name = 'userProfile/cart_list.html'
    context_object_name = 'cartItems_list'

    def get_queryset(self):
        return CartItems.objects.filter(user=self.request.user)


def remove_from_cart(request, slug):
    product = Product.objects.get(slug=slug)
    user = request.user
    cart = Cart.objects.filter(user=user, is_paid=False)

    if cart.exists():
        order = cart[0]
        if order.items.filter(product__slug=product.slug).exists():
            cart_item = CartItems.objects.filter(
                product=product, user=user, is_paid=False)[0]
            order.items.remove(cart_item)
            cart_item.delete()
        else:
            # cart item not present in cart message
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        # cart empty / user doesn't have an order message
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def remove_singleitem_from_cart(request, slug):
    product = Product.objects.get(slug=slug)
    user = request.user
    cart = Cart.objects.filter(user=user, is_paid=False)

    if cart.exists():
        order = cart[0]
        if order.items.filter(product__slug=product.slug).exists():
            cart_item = CartItems.objects.filter(
                product=product, user=user, is_paid=False)[0]
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
        else:
            # cart item not present in cart message
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        # cart empty / user doesn't have an order message
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def checkout(request):
    return render(request, 'userProfile/checkout.html')


class RegisterUser(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'userProfile/register.html'

userProfile/templates/userProfile/cart_list.html
{% extends 'base.html' %} {% block 'content' %}
<div class="row">
  <div class="col-12 mt-3 text-center text-uppercase">
    <h2>Shopping Cart</h2>
  </div>
</div>

<main class="row">
  <div class="col-12 bg-white py-3 mb-3">
    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-10 mx-auto table-responsive">
        <form class="row">
          <div class="col-12">
            <table class="table table-striped table-hover table-sm">
              <caption></caption>
              <thead>
                <tr>
                  <th scope="col">Product</th>
                  <th scope="col">Price</th>
                  <th scope="col">Qty</th>
                  <th scope="col">Amount</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for item in cartItems_list %}
                <tr>
                  <td>
                    <img
                      src="/media/{{item.product.product_image}}"
                      class="img-fluid"
                      alt="product_image"
                    />
                    {{item.product.product_name}}
                  </td>
                  <td>${{item.product.price}}</td>
                  <td>
                    <a
                      href="{% url 'userProfile:remove_singleitem' item.product.slug%}"
                      style="text-decoration: none"
                      ><i class="fas fa-minus"></i
                    ></a>
                    {{item.quantity}}
                    <a
                      href="{% url 'userProfile:add_to_cart' item.product.slug%}"
                      style="text-decoration: none"
                      ><i class="fas fa-plus"></i
                    ></a>
                  </td>
                  <td>${{item.get_total_cartitem_price}}</td>
                  <td>
                    <a
                      href="{% url 'userProfile:remove_from_cart' item.product.slug%}"
                      class="btn btn-link text-danger"
                    >
                      <i class="fas fa-times"></i>
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
              <tfoot>
                <tr>
                  <th scope colspan="3" class="text-right">Total</th>
                  <th scope>
                    $ {% for item in cartItems_list %} {% if forloop.first %}
                    {{item.get_total_amount}} {%endif%} {% endfor %}
                  </th>
                  <th scope></th>
                </tr>
              </tfoot>
            </table>
          </div>
          <div class="col-12 text-right">
            <a href={% url 'userProfile:checkout' %} class="btn btn-outline-success">Checkout</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

userProfile/templates/userProfile/checkout.html
{% extends 'base.html' %} {% block 'content' %}
<h1>Checkout Page</h1>
{% endblock %}

userProfile/templates/userProfile/register.html
{% extends 'base.html' %} {% block 'content' %}
<div class="row">
  <div class="col-12 mt-3 text-center text-uppercase">
    <h2>Register</h2>
  </div>
</div>

<main class="row">
  <div class="col-lg-4 col-md-6 col-sm-8 mx-auto bg-white py-3 mb-4">
    <div class="row">
      <div class="col-12">
        <form method="POST">
          {% csrf_token %}
          <div class="form-control">{{form.as_p}}</div>
          <div class="form-group">
            <input
              type="submit"
              class="btn btn-outline-dark"
              value="Register"
            />
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}