eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('userProfile/', include('userProfile.urls')),
    path("accounts/", include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetail, FilteredView, search_products

app_name = "products"

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path("search/", search_products, name="search_products"),
    path('<slug>/', ProductDetail.as_view(), name='product_details'),
    path("products/<slug>/", FilteredView.as_view(), name="category")
]

userProfile/urls.py
from django.urls import path
from .views import add_to_cart, CartView, remove_from_cart, remove_singleitem_from_cart, checkout, RegisterUser

app_name = "userProfile"

urlpatterns = [
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>',
         remove_from_cart, name='remove_from_cart'),
    path('remove-singleitem-from-cart/<slug>',
         remove_singleitem_from_cart, name='remove_singleitem'),
    path('cart/', CartView.as_view(), name='cart'),
    path("checkout/", checkout, name="checkout"),
    path("register/", RegisterUser.as_view(), name="register")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>E-Commerce</title>

    <link href="//fonts.googleapis.com/css?family=Righteous" rel="stylesheet" />
    <link
      href="//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i,700"
      rel="stylesheet"
    />
    <link
      href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="/media/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/media/css/all.min.css" />
    <link rel="stylesheet" href="/media/css/style.css" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row min-vh-100">
        <div class="col-12">
          <header class="row">
            <!-- Top Nav -->
            <div class="col-12 bg-dark py-2 d-md-block d-none">
              <div class="row">
                <div class="col-auto me-auto">
                  <ul class="top-nav">
                    <li>
                      {% if user.is_authenticated %}
                      <a href="#"
                        >Welcome! {{user.get_username}}</a
                      >
                      {% endif %}
                      
                    </li>
                  </ul>
                </div>
                <div class="col-auto">
                  <ul class="top-nav">
                      {% if user.is_authenticated %}
                      <li>
                        <a href="{% url 'logout' %}?next={{request.path}}"
                          ><i class="fas fa-sign-in-alt me-2"></i>Logout</a
                        >
                      </li>
                      {% else %}
                      <li>
                        <a href={% url 'userProfile:register' %}
                          ><i class="fas fa-user-edit me-2"></i>Register</a
                        >
                      </li>
                      <li>
                        <a href="{% url 'login' %}?next={{request.path}}"
                          ><i class="fas fa-sign-in-alt me-2"></i>Login</a
                        >
                      </li>
                      {% endif %}
                  </ul>
                </div>
              </div>
            </div>
            <!-- Top Nav -->

            <!-- Header -->
            <div class="col-12 bg-white pt-4">
              <div class="row">
                <div class="col-lg-auto">
                  <div class="site-logo text-center text-lg-left">
                    <a href={% url 'products:products' %}>
                      E-Commerce
                    </a>
                  </div>
                </div>
                <div class="col-lg-5 mx-auto mt-4 mt-lg-0">
                  <form action={% url 'products:search_products' %} method="GET">
                    {% csrf_token %}
                    <div class="form-group">
                      <div class="input-group">
                        <input
                          type="search"
                          name="q"
                          class="form-control border-dark"
                          placeholder="Search..."
                          required
                        />
                        <input type="submit" class="btn btn-outline-dark" value="Search"/>
                      </div>
                    </div>
                  </form>
                </div>
                <div
                  class="col-lg-auto text-center text-lg-left header-item-holder"
                >
                  <a href="#" class="header-item">
                    <i class="fas fa-heart me-2"></i
                    >
                  </a>
                  <a href={% url 'userProfile:cart' %} class="header-item">
                    <i class="fas fa-shopping-bag me-2"></i
                    >
                  </a>
                </div>
              </div>

              <!-- Nav -->
              <div class="row">
                <nav
                  class="navbar navbar-expand-lg navbar-light bg-white col-12"
                >
                  <button
                    class="navbar-toggler d-lg-none border-0"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#mainNav"
                  >
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="mainNav">
                    {% block 'filters' %}{% endblock  %}
                  </div>
                </nav>
              </div>
              <!-- Nav -->
            </div>
            <!-- Header -->
          </header>
        </div>

        <div class="col-12">
          <!-- Main Content -->
          <main class="row">{% block 'content' %}{% endblock %}</main>
          <!-- Main Content -->
        </div>

        <div class="col-12 align-self-end">
          <!-- Footer -->
          <footer class="row">
            <div class="col-12 bg-dark text-white pb-3 pt-5">
              <div class="row">
                <div
                  class="col-lg-2 col-sm-4 text-center text-sm-left mb-sm-0 mb-3"
                >
                  <div class="row">
                    <div class="col-12">
                      <div class="footer-logo">
                        <a href="index.html">E-Commerce</a>
                      </div>
                    </div>
                    <div class="col-12">
                      <address>
                        221B Baker Street<br />
                        London, England
                      </address>
                    </div>
                    <div class="col-12">
                      <a href="#" class="social-icon"
                        ><i class="fab fa-facebook-f"></i
                      ></a>
                      <a href="#" class="social-icon"
                        ><i class="fab fa-twitter"></i
                      ></a>
                      <a href="#" class="social-icon"
                        ><i class="fab fa-pinterest-p"></i
                      ></a>
                      <a href="#" class="social-icon"
                        ><i class="fab fa-instagram"></i
                      ></a>
                      <a href="#" class="social-icon"
                        ><i class="fab fa-youtube"></i
                      ></a>
                    </div>
                  </div>
                </div>
                <div
                  class="col-lg-3 col-sm-8 text-center text-sm-left mb-sm-0 mb-3"
                >
                  <div class="row">
                    <div class="col-12 text-uppercase">
                      <h4>Who are we?</h4>
                    </div>
                    <div class="col-12 text-justify">
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Nullam imperdiet vel ligula vel sodales. Aenean vel
                        ullamcorper purus, ac pharetra arcu. Nam enim velit,
                        ultricies eu orci nec, aliquam efficitur sem. Quisque in
                        sapien a sem vestibulum volutpat at eu nibh. Suspendisse
                        eget est metus. Maecenas mollis quis nisl ac malesuada.
                        Donec gravida tortor massa, vitae semper leo sagittis a.
                        Donec augue turpis, rutrum vitae augue ut, venenatis
                        auctor nulla. Sed posuere at erat in consequat. Nunc
                        congue justo ut ante sodales, bibendum blandit augue
                        finibus.
                      </p>
                    </div>
                  </div>
                </div>
                <div
                  class="col-lg-2 col-sm-3 col-5 ms-lg-auto ms-sm-0 ms-auto mb-sm-0 mb-3"
                >
                  <div class="row">
                    <div class="col-12 text-uppercase">
                      <h4>Quick Links</h4>
                    </div>
                    <div class="col-12">
                      <ul class="footer-nav">
                        <li>
                          <a href="#">Home</a>
                        </li>
                        <li>
                          <a href="#">Contact Us</a>
                        </li>
                        <li>
                          <a href="#">About Us</a>
                        </li>
                        <li>
                          <a href="#">Privacy Policy</a>
                        </li>
                        <li>
                          <a href="#">Terms & Conditions</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-1 col-sm-2 col-4 me-auto mb-sm-0 mb-3">
                  <div class="row">
                    <div class="col-12 text-uppercase text-underline">
                      <h4>Help</h4>
                    </div>
                    <div class="col-12">
                      <ul class="footer-nav">
                        <li>
                          <a href="#">FAQs</a>
                        </li>
                        <li>
                          <a href="#">Shipping</a>
                        </li>
                        <li>
                          <a href="#">Returns</a>
                        </li>
                        <li>
                          <a href="#">Track Order</a>
                        </li>
                        <li>
                          <a href="#">Report Fraud</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-sm-6 text-center text-sm-left">
                  <div class="row">
                    <div class="col-12 text-uppercase">
                      <h4>Newsletter</h4>
                    </div>
                    <div class="col-12">
                      <form action="#">
                        <div class="mb-3">
                          <input
                            type="text"
                            class="form-control"
                            placeholder="Enter your email..."
                            required
                          />
                        </div>
                        <div class="mb-3">
                          <button class="btn btn-outline-light text-uppercase">
                            Subscribe
                          </button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </footer>
          <!-- Footer -->
        </div>
      </div>
    </div>

    <script type="text/javascript" src="/media/js/jquery.min.js"></script>
    <script type="text/javascript" src="/media/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/media/js/script.js"></script>
  </body>
</html>