eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('userProfile/', include('userProfile.urls')),
    path("accounts/", include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetail, FilteredView, search_products

app_name = "products"

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path("search/", search_products, name="search_products"),
    path('<slug>/', ProductDetail.as_view(), name='product_details'),
    path("products/<slug>/", FilteredView.as_view(), name="category")
]

userProfile/urls.py
from django.urls import path
from .views import add_to_cart, CartView, remove_from_cart, remove_singleitem_from_cart, checkout, RegisterUser

app_name = "userProfile"

urlpatterns = [
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>',
         remove_from_cart, name='remove_from_cart'),
    path('remove-singleitem-from-cart/<slug>',
         remove_singleitem_from_cart, name='remove_singleitem'),
    path('cart/', CartView.as_view(), name='cart'),
    path("checkout/", checkout, name="checkout"),
    path("register/", RegisterUser.as_view(), name="register")
]

products/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    CATEGORIES = (
        ('COMPUTERS', 'computers'),
        ('MOBILES', 'mobiles'),
        ('TVs', 'tvs'),
        ('CAMERAS', 'cameras'),
        ('SPEAKERS', 'speakers')
    )
    category_name = models.CharField(
        max_length=10, choices=CATEGORIES, default='COMPUTERS')
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self):
        self.slug = slugify(self.category_name)
        super(Category, self).save()

    def __str__(self):
        return f"Category: {self.category_name}"


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    product_name = models.CharField(max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    price = models.IntegerField()
    product_description = models.TextField()
    product_image = models.ImageField(
        upload_to='products', default="/media/images/no_product_image.png")
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self):
        self.slug = slugify(self.product_name)
        super(Product, self).save()

    def __str__(self):
        return f"Product: {self.product_name} {self.price} {self.product_description}"

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product, Category
# Create your views here.


class ProductsView(ListView):
    model = Product
    template_name = "products/product_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categorys"] = Category.objects.all()
        return context


class ProductDetail(DetailView):
    model = Product


class FilteredView(ListView):
    model = Product
    template_name = "products/product_filtered_list.html"
    paginate_by = 5

    def get_queryset(self):
        products = Product.objects.filter(category__slug=self.kwargs['slug'])
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categorys"] = Category.objects.all()
        return context


def search_products(request):
    query_dict = request.GET
    query = query_dict.get("q")  # <input type="search" name="q"/>
    product = None
    if query is not None:
        product = Product.objects.get(product_name__contains=query)
    context = {
        'product': product
    }
    return render(request, 'products/search.html', context=context)

products/templates/products/product_detail.html
{% extends 'base.html' %} {% block 'content' %}
<div class="col-12 bg-white py-3 my-3">
  <div class="row">
    <!-- Product Images -->
    <div class="col-lg-5 col-md-12 mb-3">
      <div class="col-12 mb-3">
        <div class="img-large border">
          <img
            src="/media/{{product.product_image}}"
            alt="no_image"
            width="500px"
            height="400px"
          />
        </div>
      </div>
    </div>
    <!-- Product Images -->

    <!-- Product Info -->
    <div class="col-lg-5 col-md-9">
      <div class="col-12 product-name large">{{product.product_name}}</div>
      <div class="col-12 px-0">
        <hr />
      </div>
      <div class="col-12">
        <p>{{product.product_description}}</p>
      </div>
    </div>
    <!-- Product Info -->

    <!-- Sidebar -->
    <div class="col-lg-2 col-md-3 text-center">
      <div class="col-12 sidebar h-100">
        <div class="row">
          <div class="col-12">
            <span class="detail-price">${{product.price}}</span>
          </div>
          <div class="col-xl-5 col-md-9 col-sm-3 col-5 mx-auto mt-3">
          </div>
          <div class="col-12 mt-3">
            <a href={% url 'userProfile:add_to_cart' product.slug%} class="btn btn-outline-dark" type="button">
              <i class="fas fa-cart-plus me-2"></i>Add to cart
            </a>
          </div>
          <div class="col-12 mt-3">
            <button class="btn btn-outline-secondary btn-sm" type="button">
              <i class="fas fa-heart me-2"></i>Add to wishlist
            </button>
          </div>
        </div>
      </div>
    </div>
    <!-- Sidebar -->
  </div>
</div>

<div class="col-12 mb-3 py-3 bg-white text-justify">
  <div class="row">
    <!-- Ratings & Reviews -->
    <div class="col-md-5">
      <div class="col-12 px-md-4 sidebar h-100">
        <!-- Rating -->
        <div class="row">
          <div class="col-12 mt-md-0 mt-3 text-uppercase">
            <h2><u>Ratings & Reviews</u></h2>
          </div>
          <div class="col-12">
            <div class="row">
              <div class="col-sm-4 text-center">
                <div class="row">
                  <div class="col-12 average-rating">4.1</div>
                  <div class="col-12">of 100 reviews</div>
                </div>
              </div>
              <div class="col">
                <ul class="rating-list mt-3">
                  <li>
                    <div class="progress">
                      <div
                        class="progress-bar bg-dark"
                        role="progressbar"
                        style="width: 45%"
                        aria-valuenow="45"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      >
                        45%
                      </div>
                    </div>
                    <div class="rating-progress-label">
                      5<i class="fas fa-star ms-1"></i>
                    </div>
                  </li>
                  <li>
                    <div class="progress">
                      <div
                        class="progress-bar bg-dark"
                        role="progressbar"
                        style="width: 30%"
                        aria-valuenow="30"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      >
                        30%
                      </div>
                    </div>
                    <div class="rating-progress-label">
                      4<i class="fas fa-star ms-1"></i>
                    </div>
                  </li>
                  <li>
                    <div class="progress">
                      <div
                        class="progress-bar bg-dark"
                        role="progressbar"
                        style="width: 15%"
                        aria-valuenow="15"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      >
                        15%
                      </div>
                    </div>
                    <div class="rating-progress-label">
                      3<i class="fas fa-star ms-1"></i>
                    </div>
                  </li>
                  <li>
                    <div class="progress">
                      <div
                        class="progress-bar bg-dark"
                        role="progressbar"
                        style="width: 7%"
                        aria-valuenow="7"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      >
                        7%
                      </div>
                    </div>
                    <div class="rating-progress-label">
                      2<i class="fas fa-star ms-1"></i>
                    </div>
                  </li>
                  <li>
                    <div class="progress">
                      <div
                        class="progress-bar bg-dark"
                        role="progressbar"
                        style="width: 3%"
                        aria-valuenow="3"
                        aria-valuemin="3"
                        aria-valuemax="100"
                      >
                        3%
                      </div>
                    </div>
                    <div class="rating-progress-label">
                      1<i class="fas fa-star ms-1"></i>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- Rating -->

        <div class="row">
          <div class="col-12 px-md-3 px-0">
            <hr />
          </div>
        </div>

        <!-- Add Review -->
        <div class="row">
          <div class="col-12">
            <h4>Add Review</h4>
          </div>
          <div class="col-12">
            <form>
              <div class="mb-3">
                <textarea
                  class="form-control"
                  placeholder="Give your review"
                ></textarea>
              </div>
              <div class="mb-3">
                <div
                  class="d-flex ratings justify-content-end flex-row-reverse"
                >
                  <input
                    type="radio"
                    value="5"
                    name="rating"
                    id="rating-5"
                  /><label for="rating-5"></label>
                  <input
                    type="radio"
                    value="4"
                    name="rating"
                    id="rating-4"
                  /><label for="rating-4"></label>
                  <input
                    type="radio"
                    value="3"
                    name="rating"
                    id="rating-3"
                  /><label for="rating-3"></label>
                  <input
                    type="radio"
                    value="2"
                    name="rating"
                    id="rating-2"
                  /><label for="rating-2"></label>
                  <input
                    type="radio"
                    value="1"
                    name="rating"
                    id="rating-1"
                    checked
                  /><label for="rating-1"></label>
                </div>
              </div>
              <div class="mb-3">
                <button class="btn btn-outline-dark">Add Review</button>
              </div>
            </form>
          </div>
        </div>
        <!-- Add Review -->

        <div class="row">
          <div class="col-12 px-md-3 px-0">
            <hr />
          </div>
        </div>

        <!-- Review -->
        <div class="row">
          <div class="col-12">
            <!-- Comments -->
            <div class="col-12 text-justify py-2 px-3 mb-3 bg-gray">
              <div class="row">
                <div class="col-12">
                  <strong class="me-2">Steve Rogers</strong>
                  <small>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                  </small>
                </div>
                <div class="col-12">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
                  ut ullamcorper quam, non congue odio.
                  <br />
                  Fusce ligula augue, faucibus sed neque non, auctor rhoncus
                  enim. Sed nec molestie turpis. Nullam accumsan porttitor
                  rutrum. Curabitur eleifend venenatis volutpat.
                  <br />
                  Aenean faucibus posuere vehicula.
                </div>
                <div class="col-12">
                  <small> <i class="fas fa-clock me-2"></i>5 hours ago </small>
                </div>
              </div>
            </div>
            <!-- Comments -->

            <!-- Comments -->
            <div class="col-12 text-justify py-2 px-3 mb-3 bg-gray">
              <div class="row">
                <div class="col-12">
                  <strong class="me-2">Bucky Barns</strong>
                  <small>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                  </small>
                </div>
                <div class="col-12">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
                  ut ullamcorper quam, non congue odio.
                  <br />
                  Aenean faucibus posuere vehicula.
                </div>
                <div class="col-12">
                  <small> <i class="fas fa-clock me-2"></i>5 hours ago </small>
                </div>
              </div>
            </div>
            <!-- Comments -->
          </div>
        </div>
        <!-- Review -->
      </div>
    </div>
    <!-- Ratings & Reviews -->
  </div>
</div>

<!-- Similar Product -->

{% endblock %}

products/templates/products/product_filtered_list.html
{% extends 'base.html' %} 
{% block 'filters' %}
<ul class="navbar-nav mx-auto mt-2 mt-lg-0">
  <li class="nav-item active">
    <a class="nav-link" href={% url 'products:products' %}
      >Home <span class="sr-only">(current)</span></a
    >
  </li>
  {% for category in categorys %}
  <li class="nav-item">
    <a class="nav-link" href={% url 'products:category' category.slug%}>
      {{category.category_name}}
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock  %}
{% block 'content' %}
{% for product in object_list %} 
<div class="col-lg-3 col-sm-6 my-3">
  <div class="col-12 bg-white text-center h-100 product-item">
    <div class="row h-100">
      <div class="col-12 p-0 mb-3">
        <a href={% url 'products:product_details' product.slug %}>
          <img src="/media/{{product.product_image}}" width="250px" hight="250px" alt='product_image'/>
        </a>
      </div>
      <div class="col-12 mb-3">
        <a href={% url 'products:product_details' product.slug %} class="product-name">{{product.product_name}}</a>
      </div>
      <div class="col-12 mb-3">
        <span class="product-price">${{product.price}}</span>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %} 
{% block 'filters' %}
<ul class="navbar-nav mx-auto mt-2 mt-lg-0">
  <li class="nav-item active">
    <a class="nav-link" href={% url 'products:products' %}
      >Home <span class="sr-only">(current)</span></a
    >
  </li>
  {% for category in categorys %}
  <li class="nav-item">
    <a class="nav-link" href={% url 'products:category' category.slug%}>
      {{category.category_name}}
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock  %}
{% block 'content' %}<h1>All Products</h1> {% for product in object_list %}
<div class="col-lg-3 col-sm-6 my-3">
  <div class="col-12 bg-white text-center h-100 product-item">
    <div class="row h-100">
      <div class="col-12 p-0 mb-3">
        <a href={% url 'products:product_details' product.slug %}>
          <img src="/media/{{product.product_image}}" width="250px" hight="250px" alt='product_image'/>
        </a>
      </div>
      <div class="col-12 mb-3">
        <a href={% url 'products:product_details' product.slug %} class="product-name">{{product.product_name}}</a>
      </div>
      <div class="col-12 mb-3">
        <span class="product-price">${{product.price}}</span>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

products/templates/products/search.html
{% extends 'base.html' %}
{% block 'content' %}
<h1>Search Results</h1>
<div class="col-lg-3 col-sm-6 my-3">
  <div class="col-12 bg-white text-center h-100 product-item">
    <div class="row h-100">
      <div class="col-12 p-0 mb-3">
        <a href={% url 'products:product_details' product.slug %}>
          <img src="/media/{{product.product_image}}" width="250px" hight="250px" alt='product_image'/>
        </a>
      </div>
      <div class="col-12 mb-3">
        <a href={% url 'products:product_details' product.slug %} class="product-name">{{product.product_name}}</a>
      </div>
      <div class="col-12 mb-3">
        <span class="product-price">${{product.price}}</span>
      </div>
    </div>
  </div>
</div>
{% endblock  %}